const config = {
    path: process.cwd(),
    limit: 1024 * 1024,
    ignore: [
        ".git",
        ".svn",
        ".hg",
        "node_modules",
        "npm-debug.log",
        "yarn.lock",
        "bun.lock",
        "pnpm-lock.yaml",
        ".eslintcache",
        ".next",
        "dist",
        "build",
        "out",
        "__pycache__",
        ".Python",
        "env",
        "venv",
        "pip-log.txt",
        "pip-delete-this-directory.txt",
        ".mypy_cache",
        ".pytest_cache",
        ".tox",
        "target",
        "Cargo.lock",
        "cmake-build-*/",
        "build/",
        ".build/",
        "Makefile.old",
        "pm_to_blib",
        ".stack-work/",
        "dist-newstyle/",
        ".idea/",
        ".vscode/",
        ".DS_Store",
        ".env",
        ".coverage",
    ],
    ignore_regex: [
        "\\*.py[cod]",
        "\\*.o",
        "\\*.obj",
        "\\*.so",
        "\\*.dll",
        "\\*.exe",
        "\\*.dSYM",
        "\\*.swp",
        "\\*.swo",
        "\\*.log",
        "\\*.tmp",
        "\\*.bak",
        "\\*.cache",
    ],
};

export default config;
