import type { ContexoConfig } from "../core/types";

export const DEFAULT_CONFIG = {
  path: process.cwd(),
  enc: "o200k_base",
  pattern: [],
  limitNested: 0,
  limitFiles: 0,
  followLink: false,
  followMount: true,
  defaultMark: "...",
  pageLines: 1,
  pageChar: 1,
  numberLine: false,
  showArgs: false,
  invocationArgs: [],
  extensionFallbacks: {
    dirs: "sh",
    list: "conf",
    local: "sh",
  },
  ignore: [
    ".git",
    ".svn",
    ".hg",
    "node_modules",
    "npm-debug.log",
    "yarn.lock",
    "bun.lock",
    "pnpm-lock.yaml",
    ".eslintcache",
    ".next",
    "dist",
    "build",
    "out",
    "__pycache__",
    ".Python",
    "env",
    "venv",
    "pip-log.txt",
    "pip-delete-this-directory.txt",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    "target",
    "Cargo.lock",
    "cmake-build-*/",
    "build/",
    ".build/",
    "Makefile.old",
    "pm_to_blib",
    ".stack-work/",
    "dist-newstyle/",
    ".idea/",
    ".vscode/",
    ".DS_Store",
    ".env",
    ".coverage",
  ],
  cliIgnore: [],
  ignoreRegex: [
    "\\*.py[cod]",
    "\\*.o",
    "\\*.obj",
    "\\*.so",
    "\\*.dll",
    "\\*.exe",
    "\\*.dSYM",
    "\\*.swp",
    "\\*.swo",
    "\\*.log",
    "\\*.tmp",
    "\\*.bak",
    "\\*.cache",
  ],
} satisfies ContexoConfig;
